# Project Specifics
projectVersion=0.9.8
modrinthId=G9eJHDO2

# Minecraft
minecraftVersion=1.21.9
minecraftRequired=>=1.21.9-
minecraftCompatible=1.21.9
yarnMappings=1.21.9+build.1
loaderVersion=0.17.3
fabricApiVersion=0.134.0+1.21.9
polymerVersion=0.14.3+1.21.10

# Plugins
systemProp.loomVersion=1.12.+
systemProp.spotlessVersion=6.+
systemProp.minotaurVersion=2.+
systemProp.quiltflowerVersion=1.+

# Gradle Extras
org.gradle.jvmargs=-Xmx2G
