# Project Specifics
projectVersion=0.9.5.1
modrinthId=G9eJHDO2

# Minecraft
minecraftVersion=1.21.5
minecraftRequired=>=1.21.5-
minecraftCompatible=1.21.5
yarnMappings=1.21.5+build.1
loaderVersion=0.16.10
fabricApiVersion=0.119.6+1.21.5
polymerVersion=0.12.1+1.21.5-rc2

# Plugins
systemProp.loomVersion=1.13.+
systemProp.minotaurVersion=2.+

# Gradle Extras
org.gradle.jvmargs=-Xmx2G
