# Project Specifics
projectVersion=0.9.9
modrinthId=G9eJHDO2

# Minecraft
minecraftVersion=1.21.11
minecraftRequired=>=1.21.11-
minecraftCompatible=1.21.11
loaderVersion=0.19.+
fabricApiVersion=0.141.4+1.21.11
polymerVersion=0.15.2+1.21.11

# Plugins
systemProp.loomVersion=1.16.+
systemProp.minotaurVersion=2.+

# Gradle Extras
org.gradle.jvmargs=-Xmx2G
