name: Bug report
description: Create a bug report to help us improve.
labels: [ 'bug' ]
type: bug

body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        What platform & version of the mod are you using?

        Example:
          - **Minecraft**: 1.21.4 Server
          - **Polysit**: 0.8.4+1.21.2
          - **Polymer**: 0.11.6+1.21.4
          - **Loader**: Fabric 0.16.10
          - **Java**: Temurin 21.0.6+7
      value: |
        - **Minecraft**:
        - **Polysit**:
        - **Polymer**:
        - **Loader**:
        - **Java**:
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: input
    attributes:
      label: Expected results
      description: What behaviour did you expect?
      placeholder: e.g. To be wither immune.
    validations:
      required: true

  - type: input
    attributes:
      label: Actual results
      description: What behaviour did you observe instead?
      placeholder: e.g. The wither destroyed it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Crash reports, server logs, screenshots and videos should go here.
    validations:
      required: false