name: Crash report
description: Submit a crash report to help us improve.
labels: [ 'bug', 'critical' ]
type: bug

body:
  - type: textarea
    attributes:
      label: Environment
      description: |
        What platform & version of the mod are you using?

        Example:
          - **Minecraft**: 1.21.4 Server
          - **Polysit**: 0.8.4+1.21.2
          - **Polymer**: 0.11.6+1.21.4
          - **Loader**: Fabric 0.16.10
          - **Java**: Temurin 21.0.6+7
      value: |
        - **Minecraft**:
        - **Polysit**:
        - **Polymer**:
        - **Loader**:
        - **Java**:
    validations:
      required: true

  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash logs
      description: |
        The crash report.

        Tip: You can click the text box then drag the files into here in place of the details tags.
      value: |
        <details><summary>Latest logs</summary>
        <!-- If your log is too long, upload it to https://mclo.gs then paste the link here. -->
        <code>

        <!-- Paste the log here. Usually located at <server-root>/logs/latest.log -->

        </code>
        </details>
        <details><summary>Crash Report</summary>
        <!-- If your crash report is too long, upload it to https://mclo.gs then paste the link here. -->
        <code>

        <!-- Paste the crash report here. Usually located at <server-root>/crash-reports/ -->

        </code></details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: Any additional logs, screenshots and videos should go here.
    validations:
      required: false