name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build and publish with Gradle
        run: ./gradlew modrinth publish
        env:
          BUILD_RELEASE: ${{github.event.prelease == false}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH}}
          CHANGELOG: ${{ github.event.release.body }}
      - name: Upload build artifacts
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'build/libs/*;!build/libs/*-sources.jar;!build/libs/*-dev.jar'
          repo-token: ${{secrets.GITHUB_TOKEN}}